#!/usr/bin/env python3
import sys, os

import matplotlib.pyplot as plt

from src.core.graphics import blockiness_calculator_graphics
from src.core.lcr_detection import ShannonDetector  
from src.core.pcb_calculation import BlockinessCalculator

TCOF = '''MAEARKRRELLPLIYHHLLRAGYVRAAREVKEQSGQKCFLAQPVTLLDIYTHWQQTSELG
        RKRKAEEDAALQAKKTRVSDPISTSESSEEEEEAEAETAKATPRLASTNSSVLGADLPSS
        MKEKAKAETEKAGKTGNSMPHPATGKTVANLLSGKSPRKSAEPSANTTLVSETEEEGSVP
        AFGAAAKPGMVSAGQADSSSEDTSSSSDETDVEGKPSVKPAQVKASSVSTKESPARKAAP
        APGKVGDVTPQVKGGALPPAKRAKKPEEESESSEEGSESEEEAPAGTRSQVKASEKILQV
        RAASAPAKGTPGKGATPAPPGKAGAVASQTKAGKPEEDSESSSEESSDSEEETPAAKALL
        QAKASGKTSQVGAASAPAKESPRKGAAPAPPGKTGPAVAKAQAGKREEDSQSSSEESDSE
        EEAPAQAKPSGKAPQVRAASAPAKESPRKGAAPAPPRKTGPAAAQVQVGKQEEDSRSSSE
        ESDSDREALAAMNAAQVKPLGKSPQVKPASTMGMGPLGKGAGPVPPGKVGPATPSAQVGK
        WEEDSESSSEESSDSSDGEVPTAVAPAQEKSLGNILQAKPTSSPAKGPPQKAGPVAVQVK
        AEKPMDNSESSEESSDSADSEEAPAAMTAAQAKPALKIPQTKACPKKTNTTASAKVAPVR
        VGTQAPRKAGTATSPAGSSPAVAGGTQRPAEDSSSSEESDSEEEKTGLAVTVGQAKSVGK
        GLQVKAASVPVKGSLGQGTAPVLPGKTGPTVTQVKAEKQEDSESSEEESDSEEAAASPAQ
        VKTSVKKTQAKANPAAARAPSAKGTISAPGKVVTAAAQAKQRSPSKVKPPVRNPQNSTVL
        ARGPASVPSVGKAVATAAQAQTGPEEDSGSSEEESDSEEEAETLAQVKPSGKTHQIRAAL
        APAKESPRKGAAPTPPGKTGPSAAQAGKQDDSGSSSEESDSDGEAPAAVTSAQVIKPPLI
        FVDPNRSPAGPAATPAQAQAASTPRKARASESTARSSSSESEDEDVIPATQCLTPGIRTN
        VVTMPTAHPRIAPKASMAGASSSKESSRISDGKKQEGPATQVSKKNPASLPLTQAALKVL
        AQKASEAQPPVARTQPSSGVDSAVGTLPATSPQSTSVQAKGTNKLRKPKLPEVQQATKAP
        ESSDDSEDSSDSSSGSEEDGEGPQGAKSAHTLGPTPSRTETLVEETAAESSEDDVVAPSQ
        SLLSGYMTPGLTPANSQASKATPKLDSSPSVSSTLAAKDDPDGKQEAKPQQAAGMLSPKT
        GGKEAASGTTPQKSRKPKKGAGNPQASTLALQSNITQCLLGQPWPLNEAQVQASVVKVLT
        ELLEQERKKVVDTTKESSRKGWESRKRKLSGDQPAARTPRSKKKKKLGAGEGGEASVSPE
        KTSTTSKGKAKRDKASGDVKEKKGKGSLGSQGAKDEPEEELQKGMGTVEGGDQSNPKSKK
        EKKKSDKRKKDKEKKEKKKKAKKASTKDSESPSQKKKKKKKKTAEQTV'''.replace(' ', '').replace('\n', '')

shannon_detector = ShannonDetector(uid = 'TCOF', sequence = TCOF)
shannon_detector.run()

blockiness_calculator = BlockinessCalculator(uid = 'TCOF', sequence = TCOF, lcr = shannon_detector.lcr)
blockiness_calculator.run()

fig = blockiness_calculator_graphics(blockiness_calculator)
plt.show()

